# Generated by Django 3.1.6 on 2021-02-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booksandmovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booksandmovies_name', models.TextField()),
                ('booksandmovies_link', models.TextField()),
                ('booksandmovies_remark', models.TextField()),
            ],
        ),
    ]
